image: node:8.9.3

before_script:
  - npm install -g yarn

stages:
  - build
  - test
  - deploy

server_tests:
  stage: test
  script:
    - cd server
    - yarn install
    - yarn test

client_tests:
  stage: test
  script:
    - cd client
    - yarn install
    - yarn test