image: docker:latest
services:
- docker:dind

variables:
  SERVER_TEST_IMAGE: registry.gitlab.com/kanehara/spotimix/server:$CI_COMMIT_REF_NAME-test
  SERVER_RELEASE_IMAGE: registry.gitlab.com/kanehara/spotimix/server:$CI_COMMIT_TAG
  SERVER_LATEST_IMAGE: registry.gitlab.com/kanehara/spotimix/server:latest
  CLIENT_TEST_IMAGE: registry.gitlab.com/kanehara/spotimix/client:$CI_COMMIT_REF_NAME-test
  CLIENT_RELEASE_IMAGE: registry.gitlab.com/kanehara/spotimix/client:$CI_COMMIT_TAG
  CLIENT_LATEST_IMAGE: registry.gitlab.com/kanehara/spotimix/client:latest
  PRODUCTION_API_HOST: https://www.spotimix.com

stages:
  - build
  - test
  - release
  - deploy

before_script:
  - docker info
  - docker login -u $GITLAB_USER -p $CI_TOKEN registry.gitlab.com

build-server:
  stage: build
  script:
    - docker build --pull --build-arg GITLAB_USER=$GITLAB_USER --build-arg CI_TOKEN=$CI_TOKEN -t $SERVER_TEST_IMAGE ./server
    - docker push $SERVER_TEST_IMAGE

build-client:
  stage: build
  script:
    - docker build --pull --build-arg API_HOST=$PRODUCTION_API_HOST -t $CLIENT_TEST_IMAGE ./client
    - docker push $CLIENT_TEST_IMAGE

test-server:
  stage: test
  script:
    - docker pull $SERVER_TEST_IMAGE
    - docker run $SERVER_TEST_IMAGE yarn test

test-client:
  stage: test
  script:
    - docker pull $CLIENT_TEST_IMAGE
    - docker run $CLIENT_TEST_IMAGE yarn test

release-server:
  stage: release
  script:
    - docker pull $SERVER_TEST_IMAGE
    - docker tag $SERVER_TEST_IMAGE $SERVER_RELEASE_IMAGE
    - docker tag $SERVER_TEST_IMAGE $SERVER_LATEST_IMAGE
    - docker push $SERVER_RELEASE_IMAGE
    - docker push $SERVER_LATEST_IMAGE
  only:
    - tags

release-client:
  stage: release
  script:
    - docker pull $CLIENT_TEST_IMAGE
    - docker tag $CLIENT_TEST_IMAGE $CLIENT_RELEASE_IMAGE
    - docker tag $CLIENT_TEST_IMAGE $CLIENT_LATEST_IMAGE
    - docker push $CLIENT_RELEASE_IMAGE
    - docker push $CLIENT_LATEST_IMAGE
  only:
    - tags

deploy:
  stage: deploy
  when: manual
  only:
    - tags
  environment:
    name: production
  script:
    - chmod +x ./bin/deploy.sh
    - ./bin/deploy.sh
