name = "mixceed"
compatibility_date = "2025-01-07"
main = "./worker/src/index.js"

[assets]
directory = "./client/dist/"
not_found_handling = "single-page-application"
binding = "ASSETS"

[vars]
APP_HOST = "https://mixceed.yohei-kanehara.workers.dev"
SPOTIFY_API_HOST = "https://api.spotify.com"
SPOTIFY_REDIRECT_URI = "https://mixceed.yohei-kanehara.workers.dev/api/callback"

[observability]
enabled = true
