export const INIT_SPOTIFY_PLAYER = 'INIT_SPOTIFY_PLAYER'
export const TOGGLE_PLAY = 'TOGGLE_PLAY'
export const PLAY_TRACKS = 'PLAY_TRACKS'
export const SEEK = 'SEEK'
export const NEXT_TRACK = 'NEXT_TRACK'
export const PREVIOUS_TRACK = 'PREVIOUS_TRACK'
