export const SET_SPOTIFY_PLAYER = 'SET_SPOTIFY_PLAYER'
export const SET_PLAYBACK_STATE = 'SET_PLAYBACK_STATE'
export const SET_PLAYBACK_STATE_POLLING_INTERVAL_ID = 'SET_PLAYBACK_STATE_POLLING_INTERVAL_ID'
export const SET_DEVICE_ID = 'SET_DEVICE_ID'
